### ISSUE TITLE
Filters do not work with iOS 17

### ISSUE THREAD

**Issue by mirrom** [boolder-org/boolder-ios#18]
Since the update to iOS 17, no filter (like circuits, projects, ticks...) is working anymore. The map still shows all boulders. I tested this on the iPhone as well as on the iPad, on both devices the filters were working fine before the update.

**Comment by nmondollot** [comment]
Hello, 
Thanks for the report!
It’s been fixed in the latest update :)

**Comment by mirrom** [comment]
Hi Nicolas,

great, that was a fast fix :) The update showed up in the App Store today, I can confirm that all the filters are working again on the iPhone as well as on the iPad. Thank you very much!

I am currently in Fontainebleau for the next week so the fix is very much appreciated! I love your app, great job so far ❤️

**Comment by nmondollot** [comment]
That’s great to hear!
Have a nice stay in Font :)

**Comment by mirrom** [comment]
Hi Nicolas,

After using your app today I would like to provide some feedback and suggestions to hopefully help to improve the user experience of the app. I really really like your app and I think this can (and hopefully will) become the best boulder app out there :) I did not want to create an issue for each suggestion because I don't know how you feel about the suggestions, so I put them as a comment here. Feel free to do whatever you want with my feedback!


### Rotating Map

The map is currently fixed towards North. This is really great for the overall orientation and as the default view. When doing a parcour though it would have helped me if the map rotates with the orientation of the device. This would feel more like a navigation system and you could just follow the path to the next boulder. Of course the app should leave it to the user which view one prefers ;)


### Swipe to the next/previous boulder

While doing a parcour it felt kind of clumsy to hit the next/previous arrow buttons to get to the next/previous boulder. For me it felt quite natural to be able to swipe right/left on the image of the current boulder in order to get to the next/previous boulder.


### Tick/Add to Projects

Currently you have to click "Save" and then "Tick" or "Add to projects". This is not a big deal, but while doing a parcour it felt like there was one unnecessary button press to add it to the tick list. So maybe it makes sense to have them as own action buttons on the boulder view directly? You could also think of having one button/icon to toggle the state of the boulder: None -> Project -> Ticked -> None.


### Tick List

The tick list is really great to have an overview of your ticked boulders and projects. After adding quite a lot of boulders to the list it becomes a bit unhandy. I would love to see an option to filter the list by ticked boulders and by projects. Also it might be nice to be able to collapse all areas and then only expand the one area you select. This could prevent quite some scrolling ;) Another nice feature would be a search functionality just for this list.

There is some other stuff one could think about (like synchronising your ticked boulders between devices, share your ticked boulders with other users, set the date of sending a boulder, ...) but at least for me the points above would already bring the app to the next level! Not sure how you feel about PRs though?

Keep up the great work! ❤️

**Comment by nmondollot** [comment]
Thanks for the great suggestions!

### Rotating map

Good idea, I hadn't really thought about it. We'll consider it in the future!

### Swipe to the next/previous boulder

That's a great idea. We actually had an implementation in the early Boolder app.
What made me remove it was that I needed to account for problems with multiple photos (which is not supported currently, but will eventually). The swipe left/right could be a good fit to show multiple photos.
But I agree that it would also be super cool the the circuit mode.
I'll think it over.

### Tick/Add to Projects

Agreed, we can make the tick action smoother.

### Tick List

Agreed. The current version is very minimal, we've got lots of ideas to make it better. 
And I like yours!


> There is some other stuff one could think about (like synchronising your ticked boulders between devices, share your ticked boulders with other users, set the date of sending a boulder, ...) but at least for me the points above would already bring the app to the next level! 

Synchronised tick list is high on our roadmap for 2024.
It will take some time to do it well on both iPhone and Android (+ backend), but we'll get there :) 

> Not sure how you feel about PRs though?

PRs are welcome!
Always best to start with small issues though. For instance, [these issues](https://github.com/boolder-org/boolder-ios/labels/good%20first%20issue).
Do you have experience in coding iPhone apps?

**Comment by mirrom** [comment]
> Thanks for the great suggestions!

Thank you, glad to help!

> The swipe left/right could be a good fit to show multiple photos. 

Ah yeah true, haven't thought about that. Also videos could be a nice feature in the future. Maybe a separate gallery view with all the medias is an option here?

> Synchronised tick list is high on our roadmap for 2024. It will take some time to do it well on both iPhone and Android (+ backend), but we'll get there :)

Really cool to hear! Losing your projects and your ticked boulders because your switch your phone would be a shame :/

> PRs are welcome! Always best to start with small issues though. For instance, [these issues](https://github.com/boolder-org/boolder-ios/labels/good%20first%20issue). Do you have experience in coding iPhone apps?

I am not a professional iOS developer. I mostly do web application development, working with e.g. NestJS or Spring Boot for backend development and Angular or React for frontend. But I started to learn Swift some time ago out of curiosity with the usual todo app and later with a bpm counter for my personal use. So just a little experience, but I would give it a shot once I'm back home and find some time :)

**Comment by nmondollot** [comment]
> Maybe a separate gallery view with all the medias is an option here?

Yes, definitely a good idea!

> I am not a professional iOS developer. I mostly do web application development, working with e.g. NestJS or Spring Boot for backend development and Angular or React for frontend. But I started to learn Swift some time ago out of curiosity with the usual todo app and later with a bpm counter for my personal use. So just a little experience, but I would give it a shot once I'm back home and find some time :)

Great! :)
