### ISSUE TITLE
Buthiers Canard & Tennis broken for me on iOs.

### ISSUE THREAD

**Issue by sanderdlm** [boolder-org/boolder-ios#19]
Since 2c2f4acdc0b0049f3fe6efe8d6020f1a45d059d9, I can see the new Buthiers areas, but the boulder pop-up doesn't open when I tap on it.

Example (sorry no video):
![IMG_0901](https://github.com/boolder-org/boolder-ios/assets/24303072/1a0fca8a-4113-4607-b854-858281bfc946)

**Comment by nmondollot** [comment]
Hello Sander,
This should work if you re-build the app.
The update on the App Store has been submitted this morning, you should see it live in 24h or 48h 🚀 
Cheers.
